---
#- name: download do arquivo consul_1.5.2_linux_amd64.zip
#  get_url:
#    url: https://releases.hashicorp.com/consul/1.5.2/consul_1.5.2_linux_amd64.zip
#    dest: /{{ workgroup_name }}/consul_1.5.2_linux_amd64.zip
- name: extraindo consul_1.5.2_linux_amd64.zip
  unarchive:
    src: /{{ workgroup_name }}/consul_1.5.2_linux_amd64.zip
    dest: /{{ workgroup_name }}/
    remote_src: yes
- name: movendo o bin√°rio para uma pasta bin
  copy:
    src: "/{{ workgroup_name }}/consul"
    dest: "/usr/local/bin/"
    remote_src: yes
    backup: yes    
