- name: instalar ntp update
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - ntpdate
    - ntp-doc
- name: atualizar rel√≥gio com servidor {{ntp_update_server}}
  command: ntpdate {{ntp_update_server}}